server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tumbler_jobs_db    # with docker
#    url: jdbc:postgresql://localhost:5432/tumbler_jobs_db     # without docker
    username: adminuser
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false